[project]
name = "advrobot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "robotframework>=7.3.2",
    "robotframework-seleniumlibrary>=6.7.1",
    "selenium>=4.34.1",
]
